import os
import pathlib


SUGGESTED_AWARDS = [
    "The Tombstone Award for Psychopathy",
    "The Kenny Award for Dying Far Too Many Times",
    "The Leek and Safe Award for Most Interesting Weaponry",
    "The Darwin Award for Death by Stupidity",
    "The Harland Quinn Golden Quill for the Most Amusing Reports",
    "The Brutus Award for Best Betrayal",
    "The Obfuscated Tutorial System Award for Silliest Pseudonym",
    "The Zaphod Beeblebrox Award for Style",
    "The Loloccoon Award for Survival",
    "The Lemming Award for the First to Die",
    "The Catherine Zentile Award for Least Innocent Innocent",
    "The Yellow Streak Award for Running Away",
    "The Laurel and Hardy award for most amusing double act",
    "The Reversed Burden of Johannes Award for unintentionally killing innocents",
    "The 'Do you have my fish?' Award for Excuse Least Likely To Get Someone To Open The Door",
    "The David and Goliath Award for Best Giant-Killing Activity by a New Player",
    "The David Duffit award for Secrecy and Deception",
    "The Mario Sainz-Martinez Award for Cowwuption",
    "The Richard Gibson Award for Marksmanship",
    "The Dr Kimble Award for Surviving the Longest Time on the Wanted List",
    "The Three Hours Early Award for Paranoia",
    "The \"Nice Try\" Award for a valiant effort",
    "The Banker's Bonus Award for Profit",
    "The Maximus Decimus Meridius Award for Best Fight to the Death",
    "The Order of the Black Coat Award for Application of the Art of Disguise",
    "The Bandwidth Bandit Award for Non-Textual Reports",
    "The Gary Lineker Award for Sportsmanship",
    "The 'Ginger Cake' Award for the 'Smoothest' Kill",
    "The 'My Hero' Award for the Biggest Fanclub",
    "The Shin Award for Inconspicuousness",
    "The Robocop Award for killing wanted criminals",
    "The Butch Cassidy Award for Most Doomed Killing Spree",
    "The Eh? Award for Weirdest Assassins Related Happening",
    "The Pistols At Dawn Award for an Addiction to Duelling",
    "The 'I Shot the Sheriff' Award for Butchering Cops",
    "The *Twitch* Award for Plot Derailment",
    "The Cuba '62 Award for Narrowly Averted Disaster",
    "The Koom Valley Award for Best Ambush",
    "The Show Must Go On Award for Devotion to The Guild",
    "The Spawncamper Award for kill farming",
    "The Couldn't Make It Up Award for Ironic Pseudonym Choice",
    "The Lawyers At Dawn Award for Disputing Everything",
    "The Love Bug Award for Unresolved Sexual Tension",
    "The My Coat Is Just Big Boned Award for Weapon Concealment",
    "The Police Hero Medal for Outstanding Service",
    "The Red/Blue Colourblind Award for Teamkilling",
    "The Three Weeks Early Award for Signing Up Early",
    "The Watcher On The Walls Award for Dedicated Ambushing",
    "The [REDACTED] Award for [REDACTED]",
    "The Fake Simon Award for Psychological Warfare",
    "The Gentleman's Award for Reverse Profit",
    "The George R. R. Martin Award for commitment to the Plot",
    "The Judas Award for trying to betray someone, but they miraculously live thanks to the power of the almighty",
    "The Kit Jenkins award for most foolish pseudonym",
    "The Mexican Standoff Award for Tensest Situation",
    "The Peace in the Middle East award for  Alliances",
    "The Speedrun Award for Rapid Target Clearing",
    "The Cugini Award for Psychofreshery",
    "The Fluffy Bunny Collective Award for the Least Threatening Alliance",
    "The Girton Award for the Kill Furthest from Cambridge",
    "The Kife Award for Worst Weapon Labelling",
    "The LinkedIn Award for Networking",
    "The Alvin, Simon, Theodore Award for Most Amusing Triple-Act",
    "The BAFTA Award for Best Actress",
    "The Charge of the Light Brigade Award for Brave but Doomed Attacks",
    "The Not Dead Yet Award for failure to admit defeat",
    "The Spawncamper Award for Cheapest Kill",
    "The Terminator Award for Best \"I'll be Back\" moment",
    "The Bartholomew Schaf Award for Information Gathering",
    "The Dante Award for Divine Comedy",
    "The 'I Have No Mouth and I Must Scream' Award for Inventive Communication",
    "The Cain Award for Killing Family Members",
    "The Fancy Seeing You Here Award for Random Encounters",
    "The Laurel Award for most amusing single-act",
    "The London Award for Excessive Firepower",
    "The Pacifist Award for Dedication to Not Using Weapons",
    "The Rasputin Award for Why Won't You Just Die?!",
    "The COVID-19 Award for Best Self Isolation",
    "The Hidden in Plain Sight Award for Worst Ambush",
    "The Martin Lester award for special (ab)use of bins",
    "The Pedant's Award for Attention to Detail",
    "The Adam Smith Award for Services to Economics",
    "The April (Liu) is Your Fool award for Going Wanted Far Too Many Times",
    "The Dirty Dozen Award for the Most Amusing Duodecuple Act",
    "The FIFA Independent Ethics Committee Award for Legitimate Business Practices",
    "The League of Super Evil Award for Non-Game Based Nefariousness",
    "The Leroy Jenkins Award for Joyfully Suicidal Activity",
    "The rotten quill award for least comprehensible yet funny reports",
    "The Vendetta Award for Best Revenge",
    "The \"Free Pizza??\" Award for Most Avoidable Death",
    "The \"Return of the King\" Award for Reappearance of a Former Player",
    "The Alanis Morrisette Award for Irony",
    "The Happy Feet Award for Bullet Dodging",
    "The Immonulus Award for the Least Dynamic Duo",
    "The Mounted Division Award for Bicycle Warfare",
    "The Nuclear Submarine Award for Mutually Assured Destruction",
    "The Other Spawncamper Award for also kill farming",
    "The Platinum Trophy Award for Completionism",
    "The Social Butterfly Knife Award for Society Sweeping",
    "The Truman Show Award for Breaking the Fourth Wall",
    "The Walter Cronkite Award for Best News Headline",
    "The Plot Subversion Award for Interrupting Monologues ",
    "The Ships in the Night Award for Completely Missing Each Other",
    "The Jeffery Archer Award for Prolific Writing",
    "The \"It's not a bug, it's a feature!\" Award for funniest AU2 mishap",
    "The MK Ultra Award for Indoctrination",
]


COLLEGES = [
    "Christ's College",
    "Churchill College",
    "Clare College",
    "Clare Hall",
    "Corpus Christi College",
    "Darwin College",
    "Downing College",
    "Emmanuel College",
    "Fitzwilliam College",
    "Girton College",
    "Gonville & Caius College",
    "Homerton College",
    "Hughes Hall",
    "Jesus College",
    "King's College",
    "Lucy Cavendish College",
    "Magdalene College",
    "Murray Edwards College",
    "Newnham College",
    "Pembroke College",
    "Peterhouse",
    "Queens' College",
    "Robinson College",
    "Selwyn College",
    "Sidney Sussex College",
    "St Catharine's College",
    "St Edmund's College",
    "St John's College",
    "Trinity College",
    "Trinity Hall",
    "Wolfson College",
    "Other (see notes)",
    "The Real World (no college)",
    "Anglia Ruskin",
    "Casual",
    "Christ's",
    "Churchill",
    "Clare",
    "Clare Hall",
    "Corpus Christi",
    "Darwin",
    "Downing",
    "Emmanuel",
    "Fitzwilliam",
    "Girton",
    "Gonville & Caius",
    "Homerton",
    "Hughes Hall",
    "Jesus",
    "King's",
    "Lucy Cavendish",
    "Magdalene",
    "Murray Edwards",
    "Newnham",
    "Pembroke",
    "Peterhouse",
    "Queens'",
    "Robinson",
    "Selwyn",
    "Sidney Sussex",
    "St Catharine's",
    "St Edmund's",
    "St John's",
    "Trinity",
    "Trinity Hall",
    "Wolfson",
]

WATER_STATUSES = [
    "No water",
    "Water with care (small water weapons only)",
    "Full water"
]

HEADLINE_TRUNCATION_CUTOFF = 50

WEBPAGE_WRITE_LOCATION = pathlib.Path.home() / "pages"

if not os.path.exists(WEBPAGE_WRITE_LOCATION):
    os.makedirs(WEBPAGE_WRITE_LOCATION)
